export const movies = [
    {
        id: 1,
        title: "The Shawshank Redemption",
        year: 1994,
        rating: 9.3,
        genres: ["Drama"],
        runtime: "2h 22m",
        director: "Frank Darabont",
        desc: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
        poster: "https://i.pinimg.com/736x/56/c7/c1/56c7c1ec648c935d3f0384fd37622fca.jpg",
        trailerId: "PLl99DlL6b4?si",
        imdbId: "tt0111161",
    },
    {
        id: 2,
        title: "The Godfather",
        year: 1972,
        rating: 9.2,
        genres: ["Drama", "Crime"],
        runtime: "2h 55m",
        director: "Francis Ford Coppola",
        desc: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        cast: ["Marlon Brando", "Al Pacino", "James Caan"],
        poster: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        trailerId: "UaVTIH8mujA",
        imdbId: "tt0068646",
    },
    {
        id: 3,
        title: "The Dark Knight",
        year: 2008,
        rating: 9.0,
        genres: ["Action", "Crime", "Drama"],
        runtime: "2h 32m",
        director: "Christopher Nolan",
        desc: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
        poster: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg",
        trailerId: "EXeTwQWrcwY",
        imdbId: "tt0468569",
    },
    {
        id: 4,
        title: "The Godfather Part II",
        year: 1974,
        rating: 9.0,
        genres: ["Drama", "Crime"],
        runtime: "3h 22m",
        director: "Francis Ford Coppola",
        desc: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
        cast: ["Al Pacino", "Robert De Niro", "Robert Duvall"],
        poster: "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        trailerId: "9O1Iy9od7-A",
        imdbId: "tt0071562",

    },
    {
        id: 5,
        title: "12 Angry Men",
        year: 1957,
        rating: 9.0,
        genres: ["Crime", "Drama"],
        runtime: "1h 36m",
        director: "Sidney Lumet",
        desc: "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
        cast: ["Henry Fonda", "Lee J. Cobb", "Martin Balsam"],
        poster: "https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_.jpg",
        trailerId: "TEN-2uTi2c0",
        imdbId: "tt0050083",
    },
    {
        id: 6,
        title: "Schindler's List",
        year: 1993,
        rating: 8.9,
        genres: ["Biography", "Drama", "History"],
        runtime: "3h 15m",
        director: "Steven Spielberg",
        desc: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
        cast: ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes"],
        poster: "https://i.pinimg.com/originals/ff/5a/a5/ff5aa5da306cb960dbbd5e40fc83d737.jpg",
        trailerId: "gG22XNhtnoY",
        imdbId: "tt0108052",
    },
    {
        id: 7,
        title: "The Lord of the Rings: The Return of the King",
        year: 2003,
        rating: 8.9,
        genres: ["Action", "Adventure", "Drama"],
        runtime: "3h 21m",
        director: "Peter Jackson",
        desc: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
        cast: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen"],
        poster: "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        trailerId: "r5X-hFf6Bwo",
        imdbId: "tt0167260",
    },
    {
        id: 8,
        title: "Pulp Fiction",
        year: 1994,
        rating: 8.9,
        genres: ["Crime", "Drama"],
        runtime: "2h 34m",
        director: "Quentin Tarantino",
        desc: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
        poster: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        trailerId: "s7EdQ4FqbhY",
        imdbId: "tt0110912",
    },
    {
        id: 9,
        title: "The Lord of the Rings: The Fellowship of the Ring",
        year: 2001,
        rating: 8.8,
        genres: ["Action", "Adventure", "Drama"],
        runtime: "2h 58m",
        director: "Peter Jackson",
        desc: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
        cast: ["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
        poster: "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_.jpg",
        trailerId: "V75dMMIW2B4",
        imdbId: "tt0120737",

    },
    {
        id: 10,
        title: "Forrest Gump",
        year: 1994,
        rating: 8.8,
        genres: ["Drama", "Romance"],
        runtime: "2h 22m",
        director: "Robert Zemeckis",
        desc: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
        cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
        poster: "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
        trailerId: "bLvqoHBptjg",
        imdbId: "tt0109830",

    },
    {
        id: 11,
        title: "Fight Club",
        year: 1999,
        rating: 8.8,
        genres: ["Drama"],
        runtime: "2h 19m",
        director: "David Fincher",
        desc: "An insomniac office worker looking for a way to change his life crosses paths with a devil-may-care soap maker and they form an underground fight club that evolves into something much, much more.",
        cast: ["Brad Pitt", "Edward Norton", "Meat Loaf"],
        poster: "https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
        trailerId: "SUXWAEX2jlg",
        imdbId: "tt0137523",

    },
    {
        id: 12,
        title: "Inception",
        year: 2010,
        rating: 8.8,
        genres: ["Action", "Adventure", "Sci-Fi"],
        runtime: "2h 28m",
        director: "Christopher Nolan",
        desc: "A thief who steals corporate secrets through use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
        poster: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg",
        trailerId: "YoHD9XEInc0",
        imdbId: "tt1375666",

    },
    {
        id: 13,
        title: "The Lord of the Rings: The Two Towers",
        year: 2002,
        rating: 8.7,
        genres: ["Action", "Adventure", "Drama"],
        runtime: "2h 59m",
        director: "Peter Jackson",
        desc: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
        cast: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
        poster: "https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        trailerId: "LbfMDwc4azU",
        imdbId: "tt0167261",

    },
    {
        id: 14,
        title: "Star Wars: Episode V - The Empire Strikes Back",
        year: 1980,
        rating: 8.7,
        genres: ["Action", "Adventure", "Fantasy"],
        runtime: "2h 4m",
        director: "Irvin Kershner",
        desc: "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued by Darth Vader and a bounty hunter named Boba Fett all over the galaxy.",
        cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
        poster: "https://m.media-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        trailerId: "JNwNXF9Y6kY",
        imdbId: "tt0080684"
    },
    {
        id: 15,
        title: "The Matrix",
        year: 1999,
        rating: 8.7,
        genres: ["Action", "Sci-Fi"],
        runtime: "2h 16m",
        director: "Lana Wachowski, Lilly Wachowski",
        desc: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
        cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
        poster: "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        trailerId: "vKQi3bBA1y8",
        imdbId: "tt0133093"
    },
    {
        id: 16,
        title: "Goodfellas",
        year: 1990,
        rating: 8.7,
        genres: ["Biography", "Crime", "Drama"],
        runtime: "2h 26m",
        director: "Martin Scorsese",
        desc: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
        cast: ["Robert De Niro", "Ray Liotta", "Joe Pesci"],
        poster: "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        trailerId: "2ilzidi_J8Q",
        imdbId: "tt0099685"
    },
    {
        id: 17,
        title: "One Flew Over the Cuckoo's Nest",
        year: 1975,
        rating: 8.7,
        genres: ["Drama"],
        runtime: "2h 13m",
        director: "Milos Forman",
        desc: "A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up the scared patients.",
        cast: ["Jack Nicholson", "Louise Fletcher", "Michael Berryman"],
        poster: "https://m.media-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
        trailerId: "OXrcDonY-B8",
        imdbId: "tt0073486"
    },
    {
        id: 18,
        title: "Seven",
        year: 1995,
        rating: 8.6,
        genres: ["Crime", "Drama", "Mystery"],
        runtime: "2h 7m",
        director: "David Fincher",
        desc: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
        cast: ["Morgan Freeman", "Brad Pitt", "Kevin Spacey"],
        poster: "https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        trailerId: "znmZoVkCjpI",
        imdbId: "tt0114369"
    },
    {
        id: 19,
        title: "It's a Wonderful Life",
        year: 1946,
        rating: 8.6,
        genres: ["Drama", "Family", "Fantasy"],
        runtime: "2h 10m",
        director: "Frank Capra",
        desc: "An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.",
        cast: ["James Stewart", "Donna Reed", "Lionel Barrymore"],
        poster: "https://i.pinimg.com/736x/55/71/42/5571420b62c96d862d5a83fcb9445e85.jpg",
        trailerId: "iLR3gZrU2Xo",
        imdbId: "tt0038650"
    },
    {
        id: 20,
        title: "The Silence of the Lambs",
        year: 1991,
        rating: 8.6,
        genres: ["Crime", "Drama", "Thriller"],
        runtime: "1h 58m",
        director: "Jonathan Demme",
        desc: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
        cast: ["Jodie Foster", "Anthony Hopkins", "Lawrence A. Bonney"],
        poster: "https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        trailerId: "W6Mm8Sbe__o",
        imdbId: "tt0102926"
    },
    
    {
        id: 21,
        title: "Saving Private Ryan",
        year: 1998,
        rating: 8.6,
        genres: ["Drama", "War"],
        runtime: "2h 49m",
        director: "Steven Spielberg",
        desc: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
        cast: ["Tom Hanks", "Matt Damon", "Tom Sizemore"],
        poster: "https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg",
        trailerId: "S1Qj_AVu2pA",
        imdbId: "tt0120815"
    },
    {
        id: 22,
        title: "City of God",
        year: 2002,
        rating: 8.6,
        genres: ["Crime", "Drama"],
        runtime: "2h 10m",
        director: "Fernando Meirelles, Kátia Lund",
        desc: "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
        cast: ["Alexandre Rodrigues", "Leandro Firmino", "Phellipe Haagensen"],
        poster: "https://i.pinimg.com/originals/c0/4e/51/c04e51397d00ba4550367df5c96b9684.jpg",
        trailerId: "dcUOO4Itgmw",
        imdbId: "tt0317248"
    },
    {
        id: 23,
        title: "Interstellar",
        year: 2014,
        rating: 8.6,
        genres: ["Adventure", "Drama", "Sci-Fi"],
        runtime: "2h 49m",
        director: "Christopher Nolan",
        desc: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
        poster: "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
        trailerId: "zSWdZVtXT7E",
        imdbId: "tt0816692"
    },
    {
        id: 24,
        title: "The Green Mile",
        year: 1999,
        rating: 8.6,
        genres: ["Crime", "Drama", "Fantasy"],
        runtime: "3h 9m",
        director: "Frank Darabont",
        desc: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
        cast: ["Tom Hanks", "Michael Clarke Duncan", "David Morse"],
        poster: "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_.jpg",
        trailerId: "Ki4haFrqSrw",
        imdbId: "tt0120689"
    },
    {
        id: 25,
        title: "Star Wars",
        year: 1977,
        rating: 8.6,
        genres: ["Action", "Adventure", "Fantasy"],
        runtime: "2h 1m",
        director: "George Lucas",
        desc: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the evil Darth Vader.",
        cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
        poster: "https://i.pinimg.com/736x/23/6c/5c/236c5c339e905a49d0398d9601bc9266.jpg",
        trailerId: "vZ734NWnAHA",
        imdbId: "tt0076759"
    },
    {
        id: 26,
        title: "Terminator 2: Judgment Day",
        year: 1991,
        rating: 8.5,
        genres: ["Action", "Sci-Fi"],
        runtime: "2h 17m",
        director: "James Cameron",
        desc: "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten year old son, John Connor, from a more advanced and powerful cyborg.",
        cast: ["Arnold Schwarzenegger", "Linda Hamilton", "Edward Furlong"],
        poster: "https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        trailerId: "CRRlbK5w8AE",
        imdbId: "tt0103064"
    },
    {
        id: 27,
        title: "Back to the Future",
        year: 1985,
        rating: 8.5,
        genres: ["Adventure", "Comedy", "Sci-Fi"],
        runtime: "1h 56m",
        director: "Robert Zemeckis",
        desc: "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the eccentric scientist Doc Brown.",
        cast: ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson"],
        poster: "https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
        trailerId: "qvsgGtivCgs",
        imdbId: "tt0088763"
    },
    {
        id: 28,
        title: "Spirited Away",
        year: 2001,
        rating: 8.6,
        genres: ["Animation", "Adventure", "Family"],
        runtime: "2h 5m",
        director: "Hayao Miyazaki",
        desc: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
        cast: ["Daveigh Chase", "Suzanne Pleshette", "Miyu Irino"],
        poster: "https://resizing.flixster.com/toMzSC_5b1NF7MxJ5-CJeL1S-Z8=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzRlY2RiZDcyLWU5ZmEtNDliMy1iOTMyLTYzNzhjY2RjOWIxNy5qcGc=",
        trailerId: "ByXuk9QqQkk",
        imdbId: "tt0245429"
    },
    {
        id: 29,
        title: "The Pianist",
        year: 2002,
        rating: 8.5,
        genres: ["Biography", "Drama", "Music"],
        runtime: "2h 30m",
        director: "Roman Polanski",
        desc: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
        cast: ["Adrien Brody", "Thomas Kretschmann", "Frank Finlay"],
        poster: "https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        trailerId: "u_jE7-6Uv7E",
        imdbId: "tt0253474"
    },
    {
        id: 30,
        title: "Parasite",
        year: 2019,
        rating: 8.5,
        genres: ["Comedy", "Drama", "Thriller"],
        runtime: "2h 12m",
        director: "Bong Joon Ho",
        desc: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        cast: ["Kang-ho Song", "Lee Sun-kyun", "Cho Yeo-jeong"],
        poster: "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg",
        trailerId: "5xH0HfJHsaY",
        imdbId: "tt6751668"
    },
    {
        id: 31,
        title: "Léon: The Professional",
        year: 1994,
        rating: 8.5,
        genres: ["Action", "Crime", "Drama"],
        runtime: "1h 50m",
        director: "Luc Besson",
        desc: "Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée and learns the assassin's trade.",
        cast: ["Jean Reno", "Gary Oldman", "Natalie Portman"],
        poster: "https://i.pinimg.com/736x/9f/54/ac/9f54ac56aa4d999c8c3c674d5ba487cb.jpg",
        trailerId: "jawVxq1Iyl0",
        imdbId: "tt0110413"
    },
    {
        id: 32,
        title: "The Lion King",
        year: 1994,
        rating: 8.5,
        genres: ["Animation", "Adventure", "Drama"],
        runtime: "1h 28m",
        director: "Roger Allers, Rob Minkoff",
        desc: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
        cast: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"],
        poster: "https://static.kinoafisha.info/k/movie_posters/1920x1080/upload/movie_posters/8/1/1/4620118/962830171653464911.jpg",
        trailerId: "lFzVJEksoDY",
        imdbId: "tt0110357"
    },
    {
        id: 33,
        title: "Gladiator",
        year: 2000,
        rating: 8.5,
        genres: ["Action", "Adventure", "Drama"],
        runtime: "2h 35m",
        director: "Ridley Scott",
        desc: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
        cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
        poster: "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        trailerId: "P5ieIbInFpg",
        imdbId: "tt0172495"
    },
    {
        id: 34,
        title: "American History X",
        year: 1998,
        rating: 8.5,
        genres: ["Crime", "Drama"],
        runtime: "1h 59m",
        director: "Tony Kaye",
        desc: "A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.",
        cast: ["Edward Norton", "Edward Furlong", "Beverly D'Angelo"],
        poster: "https://m.media-amazon.com/images/M/MV5BZTJhN2FkYWEtMGI0My00YWM4LWI2MjAtM2UwNjY4MTI2ZTQyXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_.jpg",
        trailerId: "XfQYHqsiN5g",
        imdbId: "tt0120586"
    },
    {
        id: 35,
        title: "The Departed",
        year: 2006,
        rating: 8.5,
        genres: ["Crime", "Drama", "Thriller"],
        runtime: "2h 31m",
        director: "Martin Scorsese",
        desc: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
        cast: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson"],
        poster: "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_.jpg",
        trailerId: "r-MiSNsCdQ4",
        imdbId: "tt0407887"
    },
    {
        id: 36,
        title: "The Prestige",
        year: 2006,
        rating: 8.5,
        genres: ["Drama", "Mystery", "Sci-Fi"],
        runtime: "2h 10m",
        director: "Christopher Nolan",
        desc: "After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
        cast: ["Christian Bale", "Hugh Jackman", "Scarlett Johansson"],
        poster: "https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_.jpg",
        trailerId: "RLtaA9fFNXU",
        imdbId: "tt0482571"
    },
    {
        id: 37,
        title: "Whiplash",
        year: 2014,
        rating: 8.5,
        genres: ["Drama", "Music"],
        runtime: "1h 46m",
        director: "Damien Chazelle",
        desc: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
        cast: ["Miles Teller", "J.K. Simmons", "Melissa Benoist"],
        poster: "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
        trailerId: "7d_jQycdQGo",
        imdbId: "tt2582802"
    },
    {
        id: 38,
        title: "The Usual Suspects",
        year: 1995,
        rating: 8.5,
        genres: ["Crime", "Drama", "Mystery"],
        runtime: "1h 46m",
        director: "Bryan Singer",
        desc: "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met in a seemingly random police lineup.",
        cast: ["Kevin Spacey", "Gabriel Byrne", "Chazz Palminteri"],
        poster: "https://m.media-amazon.com/images/M/MV5BYTViNjMyNmUtNDFkNC00ZDRlLThmMDUtZDU2YWE4NGI2ZjVmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        trailerId: "Q0eCiCinc4E",
        imdbId: "tt0114814"
    },
    {
        id: 39,
        title: "Casablanca",
        year: 1942,
        rating: 8.5,
        genres: ["Drama", "Romance", "War"],
        runtime: "1h 42m",
        director: "Michael Curtiz",
        desc: "A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.",
        cast: ["Humphrey Bogart", "Ingrid Bergman", "Paul Henreid"],
        poster: "https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg",
        trailerId: "BkL9l7qovsE",
        imdbId: "tt0034583"
    },
    {
        id: 40,
        title: "Hotaru no haka",
        year: 1988,
        rating: 8.5,
        genres: ["Animation", "Drama", "War"],
        runtime: "1h 29m",
        director: "Isao Takahata",
        desc: "A young boy and his little sister struggle to survive in Japan during World War II.",
        cast: ["Tsutomu Tatsumi", "Ayano Shiraishi", "Akemi Yamaguchi"],
        poster: "https://m.media-amazon.com/images/M/MV5BZmY2NjUzNDQtNTgxNC00M2Q4LTljOWQtMjNjNDBjNWUxNmJlXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg",
        trailerId: "4vPeTSRd580",
        imdbId: "tt0095327"
    },
    {
        id: 41,
        title: "The Intouchables",
        year: 2011,
        rating: 8.5,
        genres: ["Biography", "Comedy", "Drama"],
        runtime: "1h 52m",
        director: "Olivier Nakache, Éric Toledano",
        desc: "After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.",
        cast: ["François Cluzet", "Omar Sy", "Anne Le Ny"],
        poster: "https://m.media-amazon.com/images/M/MV5BMTYxNDA3MDQwNl5BMl5BanBnXkFtZTcwNTU4Mzc1Nw@@._V1_.jpg",
        trailerId: "34WIbmXkewU",
        imdbId: "tt1675434"
    },
    {
        id: 42,
        title: "Modern Times",
        year: 1936,
        rating: 8.5,
        genres: ["Comedy", "Drama", "Family"],
        runtime: "1h 27m",
        director: "Charles Chaplin",
        desc: "The Tramp struggles to live in modern industrial society with the help of a young homeless woman.",
        cast: ["Charles Chaplin", "Paulette Goddard", "Henry Bergman"],
        poster: "https://m.media-amazon.com/images/M/MV5BYjJiZjMzYzktNjU0NS00OTkxLWEwYzItYzdhYWJjN2QzMTRlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        trailerId: "NNznUyDmSFc",
        imdbId: "tt0027977"
    },
    {
        id: 43,
        title: "Once Upon a Time in the West",
        year: 1968,
        rating: 8.5,
        genres: ["Western"],
        runtime: "2h 45m",
        director: "Sergio Leone",
        desc: "A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.",
        cast: ["Henry Fonda", "Charles Bronson", "Claudia Cardinale"],
        poster: "https://i.pinimg.com/736x/31/12/ba/3112baa2e38ddb695254e5c7dc1999ea.jpg",
        trailerId: "Yw-Av9BpC-w",
        imdbId: "tt0064116"
    },
    {
        id: 44,
        title: "Psycho",
        year: 1960,
        rating: 8.5,
        genres: ["Horror", "Mystery", "Thriller"],
        runtime: "1h 49m",
        director: "Alfred Hitchcock",
        desc: "A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.",
        cast: ["Anthony Perkins", "Janet Leigh", "Vera Miles"],
        poster: "https://i.pinimg.com/736x/c1/ed/77/c1ed77b6c6aadbe3783f7533fa8c4bbd.jpg",
        trailerId: "Wz719b9QUqY",
        imdbId: "tt0054215"
    },
    {
        id: 45,
        title: "Alien",
        year: 1979,
        rating: 8.4,
        genres: ["Horror", "Sci-Fi"],
        runtime: "1h 57m",
        director: "Ridley Scott",
        desc: "After a space merchant vessel receives an unknown transmission as a distress call, one of the crew is attacked by a mysterious life form and they soon realize that its life cycle has merely begun.",
        cast: ["Sigourney Weaver", "Tom Skerritt", "John Hurt"],
        poster: "https://m.media-amazon.com/images/M/MV5BOGQzZTBjMjQtOTVmMS00NGE5LWEyYmMtOGQ1ZGZjNmRkYjFhXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
        trailerId: "jQ5lPt9edzQ",
        imdbId: "tt0078748"
    },
    {
        id: 46,
        title: "City Lights",
        year: 1931,
        rating: 8.5,
        genres: ["Comedy", "Drama", "Romance"],
        runtime: "1h 27m",
        director: "Charles Chaplin",
        desc: "With the aid of a wealthy erratic tippler, a dewy-eyed tramp who has fallen in love with a sightless flower girl accumulates money to be able to help her medically.",
        cast: ["Charles Chaplin", "Virginia Cherrill", "Florence Lee"],
        poster: "https://m.media-amazon.com/images/M/MV5BY2I4MmM1N2EtM2YzOS00OWUzLTkzYzctNDc5NDg2N2IyODJmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        trailerId: "7vl7F8S4cpQ",
        imdbId: "tt0021749"
    },
    {
        id: 47,
        title: "Rear Window",
        year: 1954,
        rating: 8.4,
        genres: ["Mystery", "Thriller"],
        runtime: "1h 52m",
        director: "Alfred Hitchcock",
        desc: "A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.",
        cast: ["James Stewart", "Grace Kelly", "Wendell Corey"],
        poster: "https://i.pinimg.com/736x/22/c5/e2/22c5e2f1246f8e868ec24cba6446cfbf.jpg",
        trailerId: "6kCcZCMYw38",
        imdbId: "tt0047396"
    },
    {
        id: 48,
        title: "Cinema Paradiso",
        year: 1988,
        rating: 8.5,
        genres: ["Drama", "Romance"],
        runtime: "2h 35m",
        director: "Giuseppe Tornatore",
        desc: "A filmmaker recalls his childhood when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
        cast: ["Philippe Noiret", "Enzo Cannavale", "Antonella Attili"],
        poster: "https://i.pinimg.com/736x/be/7a/c1/be7ac1ae179814d4d22e971e63134960.jpg",
        trailerId: "JMyVSD6OvO8",
        imdbId: "tt0095765"
    },
    {
        id: 49,
        title: "Apocalypse Now",
        year: 1979,
        rating: 8.4,
        genres: ["Drama", "Mystery", "War"],
        runtime: "2h 27m",
        director: "Francis Ford Coppola",
        desc: "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.",
        cast: ["Martin Sheen", "Marlon Brando", "Robert Duvall"],
        poster: "https://m.media-amazon.com/images/M/MV5BYmQyNTA1ZGItNjZjMi00NzFlLWEzMWEtNWMwN2Q2MjJhYzEyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
        trailerId: "9l-ViOOFH-s",
        imdbId: "tt0078788"
    },
    {
        id: 50,
        title: "Memento",
        year: 2000,
        rating: 8.4,
        genres: ["Mystery", "Thriller"],
        runtime: "1h 53m",
        director: "Christopher Nolan",
        desc: "A man with short-term memory loss attempts to track down his wife's murderer.",
        cast: ["Guy Pearce", "Carrie-Anne Moss", "Joe Pantoliano"],
        poster: "https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        trailerId: "4CV41hoyS8A",
        imdbId: "tt0209144"
    }
];